FROM SaberZA/docker-go-lang-test:gobuildimage

LABEL app="build-go-lang-test"
LABEL REPO="https://github.com/SaberZA/go-lang-test"

ENV GOROOT=/usr/lib/go \
    GOPATH=/gopath \
    GOBIN=/gopath/bin \
    PROJPATH=/gopath/src/github.com/SaberZA/go-lang-test

# Because of https://github.com/docker/docker/issues/14914
ENV PATH=$PATH:$GOROOT/bin:$GOPATH/bin

WORKDIR /gopath/src/github.com/SaberZA/go-lang-test

CMD ["make","build-alpine"]